Newsweek-clone using mainly bootstrap
Jmagero/newsweek-clone pull request #4
Opened 2020-04-22 16:42 UTC by Jmagero

In this project, I worked on making a whole website using the Bootstrap Framework. I worked on the elements we had seen previously such as Grid and Flexbox, and I included Media Queries to be able to make the website look exactly the same as the original for different screen sizes.

General requirements:
Add descriptive README file to your repositories.
Use meaningful names for your Pull Requests and add a short summary of its content
Use descriptive commit messages
Do not commit files that are not related to the project. Instead, add them to .gitignore file.
Do not commit inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.

2020-04-22 18:43 UTC, majovanilla requested changes
Hi @Jmagero :wave: 

## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.

- Always remember to activate your repo in Stickler. I cannot see your linters working!!

- You are using some hover effects that are not the same as the original page, please make them look like the Newsweek site.

- Check the commented code below and fix it.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML in the structure of your HTML file. Favor the use of `<nav>`,  `<main>`,  `<footer>`, to enclose the elements on your file. You are already using nav and footer, just add the main tag to enclose the rest of your elements.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +          </li>
Your nav elements should occupy 100% width of the navbar space. Please adjust them.
Yours:
![Screenshot from 2020-04-22 12-59-37](https://user-images.githubusercontent.com/51926937/80017036-8c7bae80-8499-11ea-8361-6d897edbf1c7.png)

Original:
![Screenshot from 2020-04-22 12-59-43](https://user-images.githubusercontent.com/51926937/80017047-91d8f900-8499-11ea-9b27-25a76b58b9cf.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +          </section>
You have this section duplicated on your page. On large screens,  you can see both.

If you want to show the sections in a different order depending on the screen size, this is not the way. There is an option called `order` (check it [here](https://css-tricks.com/almanac/properties/o/order/)) that you should use to arrange items (there's a class on bootstrap, too).

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +      <div class="row first-section-wrapper">
You shouldn't do this either. The good practice of responsive pages is not creating duplicated content, but playing with classes to re-arrange, hide, and show the elements you want. Please delete the duplicated code and use bootstrap to arrange the elements like the original page.

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +            <div class="row heros-articles">
These two sections have a different look than the original page: 
The first article should be on one line, yours is not.
The heroes of the pandemic have different font-weight and color.

![Screenshot from 2020-04-22 13-00-57](https://user-images.githubusercontent.com/51926937/80018293-6b1bc200-849b-11ea-9098-c214d8135940.png)

Original:
![Screenshot from 2020-04-22 13-01-07](https://user-images.githubusercontent.com/51926937/80018329-7a027480-849b-11ea-8556-4f05bd5caeb0.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +                </a>
The tag should be positioned on the bottom of the image. Yours have a little space.
![Screenshot from 2020-04-22 12-59-59](https://user-images.githubusercontent.com/51926937/80018440-a0281480-849b-11ea-855d-eeaaaec4afc7.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +
The images of this section have a different size than the original page. Please fix them.
Yours:
![Screenshot from 2020-04-22 13-18-09](https://user-images.githubusercontent.com/51926937/80018577-cf3e8600-849b-11ea-9ba2-abb452207bde.png)

Original:
![Screenshot from 2020-04-22 13-18-02](https://user-images.githubusercontent.com/51926937/80018588-d5ccfd80-849b-11ea-85d9-c3d66f364334.png)

The "see all features" button is on top of the image when you make the screen smaller. That shouldn't happen.

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +                <div class="row">
The articles in this section have different image sizes and titles. Please make them look like the original page.
Please edit the same on all the screen sizes.
Yours:
![Screenshot from 2020-04-22 13-19-25](https://user-images.githubusercontent.com/51926937/80018706-0f056d80-849c-11ea-838b-d55fd06e1547.png)

Original:
![Screenshot from 2020-04-22 13-19-19](https://user-images.githubusercontent.com/51926937/80018725-1462b800-849c-11ea-9ee8-376412da648c.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +        <div class="row">
This section's three side articles have a different size (see how the pass the two articles on the left). Please make them look like the original page.
Also, include the rest of the sections that are missing.
Yours:
![Screenshot from 2020-04-22 13-21-10](https://user-images.githubusercontent.com/51926937/80019038-8804c500-849c-11ea-99e2-00501cfe4d69.png)

Original:
![Screenshot from 2020-04-22 13-21-28](https://user-images.githubusercontent.com/51926937/80019046-8b984c00-849c-11ea-8b7e-b5cab9023077.png)

When you are in the tablet version, the articles on the side are overflowing the ones on the left. Please fix this:
![Screenshot from 2020-04-22 13-27-52](https://user-images.githubusercontent.com/51926937/80019451-2a24ad00-849d-11ea-8523-370973ae460e.png)

On the mobile version this section doesn't look like the original page:
The top two articles should have 100% width.
Yours:
![Screenshot from 2020-04-22 13-37-23](https://user-images.githubusercontent.com/51926937/80020380-8d630f00-849e-11ea-9321-60cfe741bfe1.png)

Original:
![Screenshot from 2020-04-22 13-37-13](https://user-images.githubusercontent.com/51926937/80020393-918f2c80-849e-11ea-9f53-2d5583beafc6.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +
This part doesn't look like the original page, yet. Take a look at the Subscribe div: it has two images together.
The Newsletter div has a different image. The titles of both have different font-size...
Yours:
![Screenshot from 2020-04-22 13-25-19](https://user-images.githubusercontent.com/51926937/80019300-edf14c80-849c-11ea-9bfd-0d3a52153cf6.png)

Original:
![Screenshot from 2020-04-22 13-25-27](https://user-images.githubusercontent.com/51926937/80019312-f184d380-849c-11ea-90cf-2b2842cf4d74.png)


On mobile, the section behaves differently on your page. Please make it look like the original.
Yours:
![Screenshot from 2020-04-22 13-38-53](https://user-images.githubusercontent.com/51926937/80020490-c307f800-849e-11ea-9855-bcd6b7e29332.png)

Original:
![Screenshot from 2020-04-22 13-39-01](https://user-images.githubusercontent.com/51926937/80020502-c69b7f00-849e-11ea-9083-474efc6808e7.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +        </a>
On the mobile version you are repeating this section before More stories. That shouldn't happen.

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +        <article class="more-stories-article d-flex border-bottom">
On the mobile version, the articles on this section are less wider than the original page. Please make them look like the original page:
![Screenshot from 2020-04-22 13-35-58](https://user-images.githubusercontent.com/51926937/80020198-3d844800-849e-11ea-94dc-0fd72802137c.png)


Original:
![Screenshot from 2020-04-22 13-36-06](https://user-images.githubusercontent.com/51926937/80020208-4117cf00-849e-11ea-90eb-85d4f85b4703.png)

2020-04-22 18:43 UTC, majovanilla commented on index.html
> +      </div>
Give more space in between the lines of the footer elements, they look cramped.
Also, check the way the elements rearrange when you change screen sizes.
![Screenshot from 2020-04-22 13-41-24](https://user-images.githubusercontent.com/51926937/80020638-fcd8fe80-849e-11ea-97e1-e77580aa8b8b.png)

Original:
![Screenshot from 2020-04-22 13-41-17](https://user-images.githubusercontent.com/51926937/80020676-07939380-849f-11ea-8e5f-61a76fd6a4d9.png)

2020-04-22 18:46 UTC, majovanilla commented on style.css
> +}
All these classes should be bootstrap classes. Please change them.

2020-04-24 20:32 UTC, Jmagero commented
Always remember to check your HTML using the validator. You have some errors and warnings. Please fix them.
![image](https://user-images.githubusercontent.com/52098394/80254297-99f48c80-8683-11ea-93c7-376ae7a9185e.png)

Always remember to activate your repo in Stickler. I cannot see your linters working!!

You are using some hover effects that are not the same as the original page, please make them look like the Newsweek site.-Fixed

Check the commented code below and fix it.-Fixed

2020-04-24 23:04 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @Jmagero :wave:
-
You have done a splendid job of implementing the required changes! :tada:  Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- Please fix this overlap during the breakpoint to medium screen at (1010 x 710) resolution change.
![clone-styling](https://user-images.githubusercontent.com/22345961/80263313-ef876400-8698-11ea-8997-d83bd1240d6b.png)
- Kindly Fix the linter errors as well.
##
Please make these changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-04-25 09:42 UTC, Jmagero commented
fixed overlap

2020-04-25 11:34 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/Jmagero/newsweek-clone/design/index.html) shows good understanding and usage of using bootstrap. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. We just need to update the live link before proceeding.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Jmagero! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-04-25 12:34 UTC, merged